products = [{
        id: 100,
        name: 'green detox juice',
        price: 60,
        instock: 10,
        description: "fresh green detox cocktail juice",
        images: "images/detox.jpg",
    },
    {
        id: 200,
        name: 'orange juice',
        price: 70,
        instock: 15,
        description: "fresh orange juice",
        images: "images/orange.jpg",
    },
    {
        id: 300,
        name: 'pineapple juice',
        price: 100,
        instock: 7,
        description: "fresh pineapple juice",
        images: "images/pineapple.jpg",
    },
    {
        id: 400,
        name: 'kiwi juice',
        price: 150,
        instock: 20,
        description: "fresh kiwi juice",
        images: "images/kiwi.jpg",
    },
    {
        id: 500,
        name: 'strawberry juice',
        price: 110,
        instock: 5,
        description: "fresh strawberry juice",
        images: "images/strawberry.jpg",
    },
    {
        id: 600,
        name: 'mango juice',
        price: 90,
        instock: 0,
        description: "fresh mango juice",
        images: "images/mango.jpg",
    },
    {
        id: 700,
        name: 'apple juice',
        price: 50,
        instock: 30,
        description: "fresh apple juice",
        images: "images/apple.jpg",
    },
    {
        id: 800,
        name: 'cocktail juice',
        price: 30,
        instock: 25,
        description: "fresh cocktail juice of 7 fruits",
        images: "images/cocktail.jpg",
    },
    {
        id: 900,
        name: 'grap juice',
        price: 80,
        instock: 10,
        description: "fresh grap juice",
        images: "images/grap.jpg",
    }
]